apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.12.0

directories:
- path: manifests/cf-deployment
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/cf-deployment
      refSelection:
        semver:
          constraints: ">=53.0.0 <54.0.0"
    includePaths:
    - cf-deployment.yml
    - operations/use-postgres.yml
    - operations/bosh-lite.yml

- path: .github/scripts
  contents:
  - path: .
    git:
      url: https://github.com/rkoster/deskrun
      ref: main
    includePaths:
    - public/nix-setup.sh
    - public/install-devbox.sh
    - public/install-docker.sh
    newRootPath: public
