#! remove-addons.yml
#! Remove addons section from the manifest
#! Addons are not compatible with bob (Bosh on Kubernetes) and need to be 
#! transformed into jobs in instance groups instead

#@ load("@ytt:overlay", "overlay")

#! Remove the addons section entirely
#@overlay/match by=overlay.all, expects="1+"
---
#@overlay/remove
addons:
